### ISSUE TITLE
Move this project to an official Mozilla repository

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#11]
With #1 and #10 resolved, this project is starting to look much better.
I think after #5 we should move this to an official Mozilla repository.

**Comment by fbertsch** [comment]
This should live in TMO eventually, per https://github.com/mozilla/telemetry-dashboard/issues/351

**Comment by georgf** [comment]
I'll still track this here, as this is a separate, blocking task from pushing/integrating into TMO.

**Comment by georgf** [comment]
This now lives under https://github.com/mozilla/probe-dictionary/.
We can pull it into TMO from that location using subrepos or similar.
