### ISSUE TITLE
Glean dictionary: Search doesn't appear to work when using the search bar

### ISSUE THREAD

**Issue by grigoryk** [mozilla/probe-dictionary#112]
When entering a search term and pressing enter, I simply get redirected to the "/?" page (so, the page just gets refreshed).

Adding `method="GET"` to the `form` tag and `name="search"` to the `input` field fixes the problem for me.

**Comment by spasovski** [comment]
Does it work alright here: https://probes.netlify.app/ ?

It might be something related to a bug that was already fixed but PTMO is a bit behind on deploys. I will see what I can do to get a new deploy out.

**Comment by grigoryk** [comment]
@spasovski it works for me on that page, yeah. (doesn't work on https://glean-dictionary.netlify.app/)

**Comment by spasovski** [comment]
Ah misunderstood. Great find thanks! Should be fixed now.

**Comment by grigoryk** [comment]
@spasovski it works now! Thanks :-)
