### ISSUE TITLE
Glean dictionary: links in metric description blend with the background

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/probe-dictionary#113]
The color of links that are within the metric description have a color that is too close to the one of the popup background, making it hard to read (see `site origins` in the image below)

![image](https://user-images.githubusercontent.com/883721/87280388-5ecf6000-c4f2-11ea-9869-40f702b6b400.png)

**Comment by spasovski** [comment]
Should be fixed now. Great find.

**Comment by Dexterp37** [comment]
Thanks! Great job in quickly fixing this!
