### ISSUE TITLE
Expiration dates aren't the most recent

### ISSUE THREAD

**Issue by mdboom** [mozilla/probe-dictionary#116]
The expiration date on some probes seems to reflect an earlier expiration date and not the most recent one.

For example:

https://glean-dictionary.netlify.app/?product=fenix&search=default_browser&metric=metrics_default_browser

shows an expiration date of 2020-03-01,

but the [current value of that probe](https://github.com/mozilla-mobile/fenix/blob/master/app/metrics.yaml#L493) is 2020-10-01.

(Don't know if this is a bug here or in the probe-scraper not collecting everything correctly, but this is where I saw it first...)

**Comment by robhudson** [comment]
For Glean probes, the probe-search which feeds probe-dictionary, uses mozilla-schema-generator currently. Both it and probeinfo show the expiry of 2020-03-01 so there must be some upstream bug that isn't updating that.

**Comment by wlach** [comment]
This appears to be a problem with the source data produced by probe scraper: https://probeinfo.telemetry.mozilla.org/glean/fenix/metrics -- I'll try to do some more investigation and file an issue there

**Comment by wlach** [comment]
> This appears to be a problem with the source data produced by probe scraper: https://probeinfo.telemetry.mozilla.org/glean/fenix/metrics -- I'll try to do some more investigation and file an issue there

This appears to have magically gone away, and I'm now seeing the correct expiry date [1] in both the old and new glean dictionaries (the latter only after mozilla/glean-dictionary#238 applied, but whatever). 

[1] 2021-08-01 =>
https://github.com/mozilla-mobile/fenix/blob/79d1c08402274a3e96efad2929d7e0a7a9b1b647/app/metrics.yaml#L687
