### ISSUE TITLE
Glean dictionary: add type specific information to the metric popup

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/probe-dictionary#117]
When looking at the [performance.time_dom_interactive](https://glean-dictionary.netlify.app/?search=performance_&metric=performance_time_dom_interactive) metric, because it's a timing distribution, we are interested in knowing what's its time unit as well, since it has implications about its resolution.

The [`time_unit` field](https://mozilla.github.io/glean/book/user/metrics/timing_distribution.html) of the metric definition can tell us this.

The field is currently not displayed on the popup with the metric data, but it should.

**Comment by wlach** [comment]
This appears to be fixed. It is implemented in the new glean dictionary as well.
