### ISSUE TITLE
Add bucket label information to histogram details

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#12]
Once we have detail views of probes per #2, we should add information about their bucket labels.
Currently there is no easy obvious place to get them (although [the simulator](https://telemetry.mozilla.org/histogram-simulator/#low=1&high=500&n_buckets=20&kind=linear&generate=normal) happens to show them if you enter all the right parameters).

**Comment by rafrombrc** [comment]
Fixed in the new probe dictionary implementation.
