### ISSUE TITLE
Keyed scalars do not have the correct location in telemetry.main

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/probe-dictionary#121]
If you look at `printing.error`, it points to `payload.processes.parent.scalars.printing_error`. This is actually a keyed scalar, so it should point to `payload.processes.parent.keyed_scalars.printing_error`.

https://probes.telemetry.mozilla.org/?search=printing+&view=detail&probeId=scalar%2Fprinting.error

**Comment by irrationalagent** [comment]
I also ran into this today. ~It looks like the probe scraper is not properly picking up the "keyed" field~. if you click through the json in the probe dictionary, the probe scraper is picking the field up, but its just not being displayed in the probe dictionary. e.g. it is set to `true` in the yaml file for this probe
https://searchfox.org/mozilla-release/source/toolkit/components/telemetry/Scalars.yaml#776

but its empty in the probe dictionary entry:
https://probes.telemetry.mozilla.org/?search=toolbar&view=detail&probeId=scalar%2Fbrowser.ui.toolbar_widgets

I think the probe dictionary code would also have to change to handle when it finds a `true` in the `keyed` field to display the right path here:

https://github.com/mozilla/probe-dictionary/blob/bc17433ee8ee10117498fd60b2fe2ce313a442b8/src/components/probeDetails.jsx#L126

**Comment by jmathies** [comment]
There's a similar issue with keyed histograms - https://probes.telemetry.mozilla.org/?search=VIDEO_VISIBLE_PLAY_TIME_MS&view=detail&probeId=histogram%2FVIDEO_VISIBLE_PLAY_TIME_MS

**Comment by Iinh** [comment]
Fixed by #128.
