### ISSUE TITLE
Wrong info around browser.ui.interaction.preferences_paneSearch

### ISSUE THREAD

**Issue by xluo-ds** [mozilla/probe-dictionary#125]
https://probes.telemetry.mozilla.org/?search=browser+ui+search&view=detail&probeId=scalar%2Fbrowser.ui.interaction.preferences_paneSearch

Not sure whether it's meant this way. In the above link it's said to be a scalar, but actually a keyed-scalar in `main` ([link](https://console.cloud.google.com/datacatalog/projects/moz-fx-data-shared-prod/locations/u[…]pdmUvdGFibGVzL21haW5fdjQ?project=moz-fx-data-shared-prod))

**Comment by jklukas** [comment]
This does seem to be the case for keyed scalars in general in the probe dictionary. So this bug is not limited to just this one keyed scalar.

**Comment by fbertsch** [comment]
It's almost definitely getting the type from the top-level `type` field, whereas `keyed` is buried deep in the details (`root.history.release[0].details.keyed`). Seems like it should be a straightforward fix to also check the latest details.

**Comment by Iinh** [comment]
Fixed by #128.
