### ISSUE TITLE
Make the header links more discoverable

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/probe-dictionary#15]
It's hard to find the "Find probes" and "Stats" links at the top of the page. We should make them more discoverable (e.g. underline them).

**Comment by JQuinnie** [comment]
Hi All,

I'd like to work on this issue, but want to make sure that I am going down the right path.
Per screenshot below, is the request to put an underline on the header/navigation titles 'Find probe' and 'Stats'? Would you like them bolded as well?

![screen shot 2018-03-06 at 1 54 39 pm](https://user-images.githubusercontent.com/29465981/37055118-7c0e200e-2146-11e8-95c8-fbf26996ca2a.png)

**Comment by chutten** [comment]
@JQuinnie You could try a few designs out and let us know which one(s) you prefer? This is a vague request, so take it in whichever direction you think is best : )

**Comment by georgf** [comment]
Looking at the top of this Github page, making them bold seems worth to try out.
It's currently easier for us to track the work in the telemetry-dashboard repository, so i moved this to mozilla/telemetry-dashboard#446 :)

**Comment by JQuinnie** [comment]
@chutten @georgf , I have the [PR](https://github.com/mozilla/probe-dictionary/pull/38) ready, let me know what you think, suggestions always welcome 😃

**Comment by georgf** [comment]
Thanks!

Could you do the PR against the mozilla/telemetry-dashboard project?
It's not the best practice, but currently it's easier to keep track of changes there.

It would be great if you can [gives us a live link](https://github.com/mozilla/telemetry-dashboard/#submitting-pull-requests-for-the-dashboard) too.

**Comment by georgf** [comment]
This happened in the telemetry-dashboard project, thanks!
