### ISSUE TITLE
Sticky search results table header

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#20]
In the search results, it would be great if the table header is always in view, no matter where you scroll to.

**Comment by chutten** [comment]
Ref: [`position: sticky`](https://developer.mozilla.org/en-US/docs/Web/CSS/position)

**Comment by spasovski** [comment]
This seems to have been implemented some time ago: https://github.com/mozilla/probe-dictionary/blob/master/explorer.css#L154 and is in the reactify branch as well. Will close for now.
