### ISSUE TITLE
Improve the C++ guard display

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#21]
In the detail view, the C++ guard field:
- should move further down
- show e.g. italic "None" when its empty

**Comment by spasovski** [comment]
As I recall the current explore.js contains a contradiction (looks for the key in the wrong part of the object) and always registers cpp_guard as `None`. The reactify branch doesn't do this though I couldn't find an example of a probe with a valid cpp_guard (my version omits the cpp_guard row when unavailable).

tl;dr: not sure if we can close this once the reactify branch is merged

**Comment by chutten** [comment]
@spasovski To find a valid `cpp_guard` you'll have to go back in time to Firefox 65 and then you should see one called `ACCESSIBILITY` on the scalar `a11y.instantiators` (see [bug](https://phabricator.services.mozilla.com/D17231#change-z9J5IdwcoPXW)).

**Comment by spasovski** [comment]
Thanks for the quick reply. I see the resultant JSON as:
![](https://i.imgur.com/PDR0Flm.png)

Edit: had a question that I found the answer to myself. Will leave the rest of this comment for reference.
