### ISSUE TITLE
Add recorded processes to Histogram detail views

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#22]
It looks like the recorded processes data is missing from the probe-scraper data.
We should add this and show it in the detail views.

**Comment by spasovski** [comment]
As far as I can tell this has been implemented for quite some time. Might be safe to close.

**Comment by spasovski** [comment]
Actually it looks like this needs some work.

**Comment by spasovski** [comment]
Fixed via: https://github.com/mozilla/probe-dictionary/pull/91
