### ISSUE TITLE
Add row to Details view for links to DXR & searchfox searches for the probe name

### ISSUE THREAD

**Issue by chutten** [mozilla/probe-dictionary#24]
For Environment stuff direct them to TelemetryEnvironment.jsm

Histograms will probably mostly work except for ones composed by macro (some families of networking probes do this)

Scalars are often composed from category&name, javascript collections can be more easily composed, so links to searches may not be as helpful.

Events... events may be tricky.

**Comment by spasovski** [comment]
Will close this for now - any further enhancements can be opened as new issues.
