### ISSUE TITLE
Back/Forward breaks if you close details with the 'x'

### ISSUE THREAD

**Issue by chutten** [mozilla/probe-dictionary#25]
STR:
1) Open a detail view
2) Click 'x' to close
3) hit the browser back button.

Basically 'x' needs to pop the history state.

**Comment by JQuinnie** [comment]
Hi @chutten @georgf ,

I'd like to take a stab at this issue. Would you like me to move this over to the telemetry dashboard issue list?

**Comment by chutten** [comment]
Please do!

**Comment by spasovski** [comment]
I believe this has been addressed in the reactify branch.

**Comment by spasovski** [comment]
The production reactified Probe Dictionary is now available at: https://probes.telemetry.mozilla.org/ and this works as expected there.
