### ISSUE TITLE
Extend the `environment.json` file

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/probe-dictionary#32]
We should add the missing environment data (see [here](https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/TelemetryEnvironment.jsm)) to the `environment.json` file

**Comment by Dexterp37** [comment]
Let's check back if we have all the fields in the file: it's missing at least `activeAddons` now.

**Comment by Shruti9520** [comment]
@Dexterp37 @georgf Can I work on this? 
Can I add missing `activeAddons` data to json file?

Thanks!

**Comment by georgf** [comment]
Hi @Shruti9520, i think this needs a little bit more research to be actionable, as we need to think about how it will work. So it doesn't make for a great mentored bug, let's look for another one :)

**Comment by Shruti9520** [comment]
@georgf Sure. :)
Thanks for informing.

**Comment by Dexterp37** [comment]
After checking, this is additionally missing more of  the `system` data: `gfx`, `sec` and `appleModelId`. #39 takes care of this.

**Comment by georgf** [comment]
What is left after this? Mostly addon data?

- [x] build
- [x] partner
- [x] profile
- [x] settings
- [x] system
- [x] addons
- [x] experiments

**Comment by Dexterp37** [comment]
Yes, it's basically addon data + the activeExperiment small stuff! I'm taking a final stab at this today ;)

**Comment by Dexterp37** [comment]
The last two items are covered by mozilla/telemetry-dashboard#517

**Comment by georgf** [comment]
This is now closed per the above, cheers!
