### ISSUE TITLE
Only show URL params that have non-default values

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#36]
We store a lot of values in the URL params. We could greatly shorten the links if we only use params for non-default values.

**Comment by Shruti9520** [comment]
@georgf Can I take this one? :)

**Comment by georgf** [comment]
Hi @Shruti9520, sure!
It's currently easier to track these issues in the telemetry-dashboard repository, so i moved this to mozilla/telemetry-dashboard#458.
Let's discuss and do the PR over there.

**Comment by spasovski** [comment]
The reactify branch already does this. We can close this upon merge.

**Comment by spasovski** [comment]
The production reactified Probe Dictionary is now available at: https://probes.telemetry.mozilla.org/ and this works as expected there.
