### ISSUE TITLE
New probes (only on Nightly or Beta) are not being rendered when searching

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/probe-dictionary#42]
When filtering the probes by name (searching), if a channel is not explicitly set (i.e. is set to `any`), probes that are not on the `release` channel are not being displayed.

This is is due to [the rendering code](https://github.com/mozilla/probe-dictionary/blob/4e6a41b8add31db12a62bb9a1ccb733335e52c50/explore.js#L446-L451) assuming that the probes are on all channels and not wanting to display multiple entries for the same probe.

**Comment by georgf** [comment]
This was fixed by one of the recent fixes as confirmed by e.g. [https://telemetry.mozilla.org/probe-dictionary/?search=telemetry_event](https://telemetry.mozilla.org/probe-dictionary/?search=telemetry_event) showing up newly in 63 nightly.
