### ISSUE TITLE
Detail view never shows bug numbers

### ISSUE THREAD

**Issue by badboy** [mozilla/probe-dictionary#43]
In the detail view of a probe, e.g. [A11Y_CONSUMERS](https://telemetry.mozilla.org/probe-dictionary/?detailView=histogram%2FA11Y_CONSUMERS), no bug numbers are shown.

[They should be](https://github.com/mozilla/probe-dictionary/blob/master/explore.js#L795-L802).

**Comment by chutten** [comment]
Near as I can tell, it's not in the data: https://probeinfo.telemetry.mozilla.org/firefox/nightly/main/all_probes

So maybe this is a Probe Info Service bug?

**Comment by chutten** [comment]
Oh look. I'm even the one who filed it: https://github.com/mozilla/probe-scraper/issues/44
