### ISSUE TITLE
Clean up references to `aurora`

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/probe-dictionary#46]
The probe scraper is not [scraping](https://github.com/mozilla/probe-scraper/blob/04b95a6da64f2ef3fdda3ad8c25811348ddd807d/probe_scraper/scrapers/moz_central_scraper.py#L29-L42) aurora data anymore. I think we can get rid of the various special case handling within `explore.js`.

**Comment by spasovski** [comment]
attempt at this at: https://github.com/mozilla/probe-dictionary/pull/63

**Comment by spasovski** [comment]
the fix for this was merged in the reactify branch, we can close this once that becomes master

**Comment by spasovski** [comment]
The production reactified Probe Dictionary is now available at: https://probes.telemetry.mozilla.org/
