### ISSUE TITLE
Possibly incorrect recording range for probe

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#48]
The [active_ticks scalar](https://telemetry.mozilla.org/probe-dictionary/?detailView=scalar%2Fbrowser.engagement.active_ticks) was never uplifted, but shows up as starting on Nightly 56 & Beta 55.

This was around the Project Dawn cycle, so something around the version tracking there might be special.

**Comment by spasovski** [comment]
This might be an issue in the probe scraper - will doublecheck that we're exposing the right key.

**Comment by spasovski** [comment]
should be fixed via https://github.com/mozilla/probe-dictionary/pull/97
