### ISSUE TITLE
Probe Dictionary Shouldn't Include Measurement Dashboard Links for Data That Won't Show Up

### ISSUE THREAD

**Issue by chutten** [mozilla/probe-dictionary#49]
It'll 404 in the backend and will display nothing helpful, so we might as well omit the link.

**Comment by georgf** [comment]
Do you have examples of data that won't show up?

**Comment by chutten** [comment]
https://telemetry.mozilla.org/probe-dictionary/?search=update&detailView=histogram%2FUPDATER_BACKGROUND_CHECK_CODE_NOTIFY

and

https://telemetry.mozilla.org/probe-dictionary/?search=update&detailView=histogram%2FUPDATER_SERVICE_ERROR_CODE

were the ones reported on #telemetry. Anything expired, and certainly anything no longer present in the definition files for the selected branch.

**Comment by chutten** [comment]
Future tools should not have the same failing where expired or absent probes have no display so we should take care of these concerns as part of that tools evolution instead.
