### ISSUE TITLE
Confusing or wrong version information about probe

### ISSUE THREAD

**Issue by felixlawrence** [mozilla/probe-dictionary#50]
I might be incorrectly reading the dictionary, but [INPUT_EVENT_RESPONSE_COALESCED_MS](https://telemetry.mozilla.org/probe-dictionary/?search=input_event_respons&detailView=histogram%2FINPUT_EVENT_RESPONSE_COALESCED_MS) claims that it was recorded in versions "release 54 to 60". It seems to still be recorded in 64 - in fact the dictionary (correctly) says that "release never expires" which is consistent with [the source](https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/Histograms.json#6590-6599).

Am I misinterpreting what "Recorded in versions" means or is it wrong?

**Comment by chutten** [comment]
Looks like it expired in 60 (see the older definition [here](https://searchfox.org/mozilla-central/rev/d34c7d9a48d43feb43ccaf9c68c8be5bef5c9f86/toolkit/components/telemetry/Histograms.json#6405-6415)) then was revived with [bug 1489524](https://bugzilla.mozilla.org/show_bug.cgi?id=1489524) to ride with 64. So it did record 54-60, then 64-onwards.

I don't think the [probe-scraper probe data file format](https://github.com/mozilla/probe-scraper/#probe-data-file) supports probes with more than one first and last revision/version, so this might require changes here.

Sorry for the confusion!

**Comment by felixlawrence** [comment]
Aha, a good ol' edge case!

**Comment by fbertsch** [comment]
It looks like the data from the [probe info service](https://probeinfo.telemetry.mozilla.org/firefox/all/main/all_probes) does have the two different definitions, but the probe-dictionary doesn't seem to be using the latest definition.

**Comment by chutten** [comment]
Hm. Seems like we use the first `last` and the last `first` to build our range: https://github.com/mozilla/probe-dictionary/blob/master/explore.js#L460

**Comment by chutten** [comment]
Looping in @georgf as code author for comments

**Comment by fbertsch** [comment]
We should be getting the `first` from the definition with the earliest `version`, and the `last` from the definition with the latest `version`. This should be a straightforward change for an external contributor.

**Comment by gijsk** [comment]
This bit me (again) today; Where exactly does this code live? And why is there a different "recorded" and "expires" row in the probe detail view?

**Comment by fbertsch** [comment]
@gijsk this is actively being worked on by @spasovski. You can see some work started on a [dev instance](https://fervent-bardeen-26250d.netlify.app/).

**Comment by gijsk** [comment]
OK, that's a bit better, but still confusing, e.g. if you filter for `READER_MODE_DOWNLOAD_RESULT` it says `to 76` in the `recorded` column. But it's set to `expires: "never"` in Histograms.json, so that's confusing. Then if you open that specific histogram, it says that beta and nightly never expire (and correctly indicates current beta/nightly versions in terms of recording), but isn't clear about release. I think all these fields should clarify that we record it "everywhere" (since version X).

**Comment by spasovski** [comment]
https://github.com/mozilla/probe-dictionary/pull/97
