### ISSUE TITLE
Multiple search terms would be nice

### ISSUE THREAD

**Issue by jtg567** [mozilla/probe-dictionary#51]
I can search for probes with the word `video` in any text field and get a number of results.

I can search for probes with the word `time` in any text field and get a number of results.

However when I type `video time`, `video and time`, or `video & time` I get no results. I presume because no text fields contain those literal phrases, not because there are no probes with both the words `video` and `time`.

**Comment by chutten** [comment]
Looks like we could change https://github.com/mozilla/probe-dictionary/blob/master/explore.js#L359 to be something like

```js
var test = (str) => s.split(" ").all(tok => str.toLowerCase().includes(tok));
```

**Comment by spasovski** [comment]
This was added to https://probe-dictionary.herokuapp.com/ via https://github.com/mozilla/probe-dictionary/commit/e2b2895

**Comment by jtg567** [comment]
Excellent!
