### ISSUE TITLE
HDD binary model says "Available in: hardware report - view what hardware and operating systems Firefox users have." although not visible in hardware report.

### ISSUE THREAD

**Issue by D4n2021** [mozilla/probe-dictionary#57]
https://telemetry.mozilla.org/probe-dictionary/?detailView=environment%2Fsystem.hdd.binary.model
there is says "Available in: hardware report - view what hardware and operating systems Firefox users have."
but when visiting https://data.firefox.com/dashboard/hardware , there are no HDD statistics visible.

**Comment by Dexterp37** [comment]
Thank you for reporting this. Looks like [we assume](https://github.com/mozilla/probe-dictionary/blob/40ffce5e09e469bf9c997ceb49caeb063da3606a/explore.js#L757-L761) that everything in `environment.system` also shows up in the Firefox Public Data, but that's not the case. We should probably adjust this special case in the code.

**Comment by fbertsch** [comment]
This should need a bit of design around what we're including.

**Comment by D4n2021** [comment]
what do you mean by "around what we're including" ? @fbertsch

**Comment by spasovski** [comment]
Are we specifically excluding only environmet/system.hdd.binary.model or do we have other edge cases as well?

**Comment by spasovski** [comment]
remove all text and link to hardware report

**Comment by spasovski** [comment]
fixed via https://github.com/mozilla/probe-dictionary/pull/93
