### ISSUE TITLE
Sort channel+ver lists to have nightly,beta,release order

### ISSUE THREAD

**Issue by chutten** [mozilla/probe-dictionary#61]
At present the "Recorded in versions" and "Expiry" rows in the details view order their channels alphabetically: beta, nightly, release.

I'm thinking we should custom-sort these to nightly, beta, release to match train order.

**Comment by spasovski** [comment]
fixed on the reactify branch via https://github.com/mozilla/probe-dictionary/commit/1d8ab7a
