### ISSUE TITLE
Remove reference to main summary for events

### ISSUE THREAD

**Issue by fbertsch** [mozilla/probe-dictionary#62]
Events have not been on the main ping since we started sending the main ping, and newer events will never show up there. We should remove the reference to main_summary on event detail pages since the events dataset includes events from both main and event pings

https://github.com/mozilla/probe-dictionary/issues/53

**Comment by spasovski** [comment]
chutten reviewed the PR for this which was just merged, should be safe to close once the reactify branch is merged

**Comment by spasovski** [comment]
The production reactified Probe Dictionary is now available at: https://probes.telemetry.mozilla.org/
