### ISSUE TITLE
Toolbar apparently inoperative when viewing a probe

### ISSUE THREAD

**Issue by martinthomson** [mozilla/probe-dictionary#65]
STR:
Search for a probe, pick one.
Click the "Stats" button at the top.

Expected:
Something happens

Actual:
Nothing happens until you click the tiny x up in the far right corner.

This looks and behaves very much like a new page, except for that little x.  But the change in style does not hint at the presence of the x and I completely missed it.  I then wondered why I couldn't see anything.

**Comment by spasovski** [comment]
This behaves as expected in the reactify branch, https://probe-dictionary.herokuapp.com/ and can probably be closed once it has been merged to master.

**Comment by spasovski** [comment]
The production reactified Probe Dictionary is now available at: https://probes.telemetry.mozilla.org/ and this works as expected there.
