### ISSUE TITLE
Remove probe filtering based on datasets.json

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/probe-dictionary#67]
In the older probe dictionary, the datasets.json file was used to specify the subset of probes that the dictionary should expose. Now that we've moved to the GCP infrastructure, all of the probes are available in our data sets, so we no longer need this filter... the probe dictionary should expose all of the probes. The means we no longer need the datasets.json mechanism to specify which probes should be shown.

**Comment by spasovski** [comment]
This PR should do it: https://github.com/mozilla/probe-dictionary/pull/71 I'd appreciate a review from @chutten or frank
