### ISSUE TITLE
"Add a keyword for this search" uses `?text_search=` instead of `?search=`

### ISSUE THREAD

**Issue by chutten** [mozilla/probe-dictionary#69]
In the React version, if you right-click>Add Keyword for this Search>(then provide a keyword). That keyword search in Firefox will have the pattern `https://probe-dictionary.herokuapp.com/?text_search=%s`

Which is a problem because the actual query param for the search term is `search`, not `text_search`

**Comment by spasovski** [comment]
done: https://github.com/mozilla/probe-dictionary/commit/c91cb07
