### ISSUE TITLE
Find new location for link to GitHub project

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#7]
We are dropping the GH banner in #1.
Maybe we can instead link to the project page in the top bar somewhere?

**Comment by hampgoodwin** [comment]
I was thinking in a footer. 
If we do it in the navigation bar right-aligned, it could look good as well.

**Comment by georgf** [comment]
I think having it right-aligned in the navigation bar would be great.
The page can have a lot of content, making it hard to discover any footer information.
