### ISSUE TITLE
Add categorical histogram lables to UI

### ISSUE THREAD

**Issue by robhudson** [mozilla/probe-dictionary#70]
In https://github.com/mozilla/probe-scraper/issues/111 we updated the probe scraper to include the labels for categorical histograms. They can be found in the `details` object of the JSON. This should be included in the UI for categorical histograms.

**Comment by spasovski** [comment]
Do you mean just a comma delimited list of the labels? Shouldn't be too tough.

**Comment by robhudson** [comment]
Yes, and in the order in the JSON b/c the pings come through with the index of the labels rather than the labels, so anyone wanting to correlate the index value with a label would need this.

**Comment by spasovski** [comment]
done: https://github.com/mozilla/probe-dictionary/commit/004ca8c

**Comment by spasovski** [comment]
The production reactified Probe Dictionary is now available at: https://probes.telemetry.mozilla.org/ and this works as expected there.
