### ISSUE TITLE
For Glean, we should support markdown in a probe's description

### ISSUE THREAD

**Issue by badboy** [mozilla/probe-dictionary#75]
Glean doesn't restrict how to format the text description of a probe.
It would be nice to support rendering Markdown, when displayed in the probe-dictionary.
The `glean_parser` is already able to generate a Markdown document from the defined metrics (e.g. see [metrics.md](https://github.com/mozilla-mobile/fenix/blob/master/docs/metrics.md) of Fenix). If there's markdown-like syntax in the description it will be unescaped in the generated docs.

I leave it to you whether we need to take any precautions in filtering anything (e.g. don't allow images or raw html tags).
For now probe-dictionary only covers Mozilla products, so we have control over what's in there.

(This is moving [Bug 1561597](https://bugzilla.mozilla.org/show_bug.cgi?id=1561597) to the right project).

**Comment by spasovski** [comment]
https://github.com/mozilla/probe-dictionary/commit/c469218
