### ISSUE TITLE
probe dictionary version expiry inconsistent / unclear

### ISSUE THREAD

**Issue by benmiroglio** [mozilla/probe-dictionary#77]
I was trying to figure out when this probe expired:

https://telemetry.mozilla.org/probe-dictionary/?search=preferences&detailView=histogram%2FFX_PREFERENCES_CATEGORY_OPENED_V2

The page above says:

**Recorded in versions:**
beta 54 to 58, nightly 55 to 58, release 54 to 58
**Expiry:**
beta stopped recording in 66, nightly stopped recording in 66, release stopped recording in 66

After some help from chutten and tdsmith, [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1502019) indicates that it indeed expired in 66, yet the most recent valid version is FF64.

I believe the **recorded in versions** section is mistake, however it also wasn't clear without that bug as a reference that I needed to filter my data to version 64.

**Comment by spasovski** [comment]
should be fixed via https://github.com/mozilla/probe-dictionary/pull/97
