### ISSUE TITLE
Stats view broken after detail view

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-dictionary#79]
* Open [this detail view](https://probes.telemetry.mozilla.org/?view=detail&probeId=histogram%2FUSE_COUNTER2_CSS_PROPERTY_WebkitBackgroundSize_DOCUMENT)
* Click *stats* button on top.
* Result: A blank white page, some errors in web console:
> TypeError: "c.history[u] is undefined"

**Comment by spasovski** [comment]
Can no longer reproduce in prod or locally - though I remember seeing it at the time you filed this. Not sure what fixed it though will close for now. Please feel free to reopen if you see this again on any other probe.
