### ISSUE TITLE
probe info service 'all_probes' request slowing down probe dictionary page load times

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/probe-dictionary#80]
(paraphrased from esmyth on slack) The https://probeinfo.telemetry.mozilla.org/firefox/all/main/all_probes GET request has a negative impact on page load times. It's a large json object (~25mb) w a short cache duration (1h), resulting in frequent hits which tank page load time. With the frequency that I visit the dictionary, this is noticeable and frustrating.

**Comment by wlach** [comment]
It seems like the content is also being served uncompressed at the moment. Using zlib or brotli compression would improve the load times by a large amount: I get a more than 25x compression on the command line with gzip:

```bash
(community-tc-config) wlach@antwerp community-tc-config % curl -O https://probeinfo.telemetry.mozilla.org/firefox/all/main/all_probes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.8M  100 24.8M    0     0  5929k      0  0:00:04  0:00:04 --:--:-- 6225k
(community-tc-config) wlach@antwerp community-tc-config % ls -alh all_probes 
-rw-r--r--  1 wlach  staff    25M 12 Feb 12:38 all_probes
(community-tc-config) wlach@antwerp community-tc-config % gzip all_probes 
(community-tc-config) wlach@antwerp community-tc-config % ls -alh all_probes.gz 
-rw-r--r--  1 wlach  staff   773K 12 Feb 12:38 all_probes.gz
```

**Comment by fbertsch** [comment]
This was fixed with @wlach's work.
