### ISSUE TITLE
Add reference to Main Ping view fields in probe view

### ISSUE THREAD

**Issue by akkomar** [mozilla/probe-dictionary#89]
Main ping BQ view should be listed as a reference data source, this should also replace a reference to main_summary.
See image below for proposed layout:
![add_probe_query_links](https://user-images.githubusercontent.com/1476307/80070902-08cacc00-8544-11ea-9bef-123090ae7ec2.png)

**Comment by spasovski** [comment]
I don't have this data in the probe scraper JSON blob. Is there a programmatic way to reliably assemble this string currently?

We have recorded_in_processes for histograms which could help with `payload.processes.content.histograms.parent.a11y_consumers`.

**Comment by akkomar** [comment]
Hey @acmiyaguchi how could we get from probe names to main ping view column names in BQ?

**Comment by acmiyaguchi** [comment]
To obtain a probe name from the main ping, it must be referred to based on the structure of the main ping and applying snake casing rules to all elements in the path. It is designed to be easy to implement in any language with regular expression support and there are test cases available for consistent implementation.

The python implementation is fairly short:

```python
import re

# Search for all camelCase situations in reverse with arbitrary lookaheads.
REV_WORD_BOUND_PAT = re.compile(
    r"""
    \b                                  # standard word boundary
    |(?<=[a-z][A-Z])(?=\d*[A-Z])        # A7Aa -> A7|Aa boundary
    |(?<=[a-z][A-Z])(?=\d*[a-z])        # a7Aa -> a7|Aa boundary
    |(?<=[A-Z])(?=\d*[a-z])             # a7A -> a7|A boundary
    """,
    re.VERBOSE,
)

def snake_case(line: str) -> str:
    # replace non-alphanumeric characters with spaces in the reversed line
    subbed = re.sub(r"[^\w]|_", " ", line[::-1])
    # apply the regex on the reversed string
    words = REV_WORD_BOUND_PAT.split(subbed)
    # filter spaces between words and snake_case and reverse again
    return "_".join([w.lower() for w in words if w.strip()])[::-1]
```

The [java implementation in gcp-ingestion](https://github.com/mozilla/gcp-ingestion/blob/master/ingestion-core/src/main/java/com/mozilla/telemetry/ingestion/core/util/SnakeCase.java) is also a good reference.

To construct the path, the logic is something similar to the following:

```
let name be the probe name
let process be one of [parent, content, gpu]
let type be one of [scalars, keyedScalars, histogram, keyedHistogram]

snakecase name, process, and type

if recorded in process:
   let path be `payload.<process>.<type>.<name>`
else:
   let path be `payload.<type>.name`
```

It would also be useful to prepopulate a query that can be run in redash e.g.

```sql
SELECT
    DATE(submission_timestamp) as submission_date,
    {{ probe }}
FROM
    telemetry.main
WHERE
    DATE(submission_timestamp) = DATE '{{ ds }}'
    AND sample_id = 1
```

**Comment by spasovski** [comment]
Super useful! Also love the generated SQL idea thanks Anthony.

**Comment by spasovski** [comment]
Looks like this would work if we want to visit PTMO in Chrome only: https://caniuse.com/#feat=js-regexp-lookbehind 

Anyone good at rewriting that regexp without lookarounds? Alternatively a python API that would let me send the string for conversion.

**Comment by acmiyaguchi** [comment]
Do you think using a wasm-compiled version of PCRE2 (https://github.com/stephen-riley/pcre2-wasm) would work? Alternatively, the information could be added to the raw data directly at the cost of size of the dictionary.

**Comment by spasovski** [comment]
I am leaning towards including this in the probe info service payload especially since that will be improved as part of the paginated probe search currently in development. It would also ensure that we're using the better tested python script.

FWIW I am seeing a lot of need for this feature and would love to expose this on the details page as soon as possible.

**Comment by mreid-moz** [comment]
Could we use something like the "reversal" approach in [this article](http://blog.stevenlevithan.com/archives/mimic-lookbehind-javascript) as a workaround?

**Comment by robhudson** [comment]
I filed the above Github issue in probe-scraper, which could be an easy addition and solve this for probe dictionary, as well as probe-search which feeds GLAM.

**Comment by spasovski** [comment]
To update folks on this...it's looking like it will land with the upcoming Probe Search integration.

**Comment by wlach** [comment]
> Looks like this would work if we want to visit PTMO in Chrome only: https://caniuse.com/#feat=js-regexp-lookbehind
> 
> Anyone good at rewriting that regexp without lookarounds? Alternatively a python API that would let me send the string for conversion.

It appears that this feature is now supported in recent versions of Firefox, so I think we can go ahead with just porting the python implementation @acmiyaguchi described in https://github.com/mozilla/probe-dictionary/issues/89#issuecomment-618608820
